require("after.nvim-tree")
require("after.treesitter")
require("after.telescope")
require("after.easymotion")
require("after.indent-blankline")
require("after.lualine")
require("after.neodev")
require("after.conform")
require("after.debugging")

vim.cmd("colorscheme catppuccin-mocha")
